apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: my-container
    image: node:16
    command: ["node", "server.js"]
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-volume
      mountPath: /usr/src/app
  volumes:
  - name: app-volume
    hostPath:
      path: .

